name:                hoodlums20180308
version:             0.1.0.0
github:              "githubuser/hoodlums20180308"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/hoodlums20180308#readme>

dependencies:
- base >= 4.7 && < 5
- vector
default-extensions:
- OverloadedLists
- BangPatterns


library:
  dependencies:
  - vector
  source-dirs: src

executables:
  hoodlums20180308-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hoodlums20180308

tests:
  hoodlums20180308-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hoodlums20180308
    - hspec
    - QuickCheck
